# Generated by Django 5.2.5 on 2025-08-28 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pais',
            options={'ordering': ['title'], 'verbose_name': 'Pais', 'verbose_name_plural': 'Paises'},
        ),
    ]
